config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  mount StripeEvent::Engine, at: '/stripe_events'

  root to: 'pages#front'

  get 'ui/:name', to: 'ui#index'

  namespace :admin do
    resources :videos, only: [:new, :create]
    resources :payments, only: [:index]
  end

  get "home", to: "videos#index"

  get "register", to: "users#new"
  get "register/:token", to: "users#new_with_invitation_token", as: "register_with_token"
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'forgot_password', to: 'forgot_passwords#new'
  resources :forgot_passwords, only: [:create]
  get 'forgot_password_confirmation', to: 'forgot_passwords#confirm'
  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: 'pages#expired_token'

  resources :users, only: [:create, :show, :update]
  get 'account', to: 'users#edit'
  get 'billing', to: 'users#plan_and_billing'
  post 'billing', to: 'users#plan_and_billing'

  resources :videos, only: [:index, :show] do
    collection do
      post :search, to: "videos#search"
      get :advanced_search, to: "videos#advanced_search"
    end

    resources :reviews, only: [:create]
  end

  resources :categories, only: [:index, :show]

  get 'my_queue', to: 'queue_items#index'
  resources :queue_items, only: [:create, :destroy]
  post 'update_queue', to: 'queue_items#update_queue'

  get 'people', to: 'relationships#index'
  resources :relationships, only: [:create, :destroy]

  resources :invitations, only: [:new, :create]
end

app/models/user.rb
class User < ActiveRecord::Base
  include Tokenable

  validates_presence_of :email, :full_name, :password
  validates_uniqueness_of :email

  has_many :reviews
  has_many :queue_items
  has_many :following_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :leading_relationships, class_name: "Relationship", foreign_key: :leader_id

  has_secure_password validations: false

  def normalize_queue_items
    queue_items.each_with_index do |item, index|
      item.update_attributes(position: index+1)
    end
  end

  def queued_video?(video)
    queue_items.map(&:video).include?(video)
  end

  def follows?(a_user)
    following_relationships.map(&:leader).include?(a_user)
  end

  def can_follow?(a_user)
    !(self.follows?(a_user) || self == a_user)
  end

  def follow(a_user)
    following_relationships.create(leader: a_user) if can_follow?(a_user)
  end

  def deactivate!
    update_column(:active, false)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: [:show]

  def new
    redirect_to home_path if current_user
    @user = User.new
  end

  def new_with_invitation_token
    invitation = Invitation.find_by(token: params[:token])
    if invitation
      @user = User.new(email: invitation.recipient_email)
      @invitation_token = invitation.token
      render :new
    else
      redirect_to expired_token_path
    end
  end

  def create
    @user = User.new(user_params)

    result = UserRegistration.new(@user).register(params[:stripeToken], params[:invitation_token])

    if result.successful?
      flash[:success] = "Welcome! Please login."
      redirect_to login_path
    else
      flash[:danger] = result.error_message
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(user_params)
      flash[:success] = "Updated Account Information"
      redirect_to home_path
    else
      render :edit
    end
  end

  def plan_and_billing
    customer = StripeWrapper::Customer.retrieve(current_user)
    @customer = StripeCustomerDecorator.new(customer)
    @invoices = StripeWrapper::Invoice.list(current_user).map { |invoice| StripeInvoiceDecorator.new(invoice) }
    cancel_subscription if params[:cancel].present?
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :full_name)
  end

  def cancel_subscription
    cancellation = StripeWrapper::Subscription.cancel_subscription(current_user)
    if cancellation.successful?
      current_user.deactivate!
      session[:user_id] = nil
      flash[:success] = "Your account is no longer active"
      redirect_to login_path
    else
      flash[:danger] = result.error_message
      render :plan_and_billing
    end
  end
end

app/views/users/edit.html.haml
%section.account.container
  .row
    .col-md-10.col-lg-offset-1
      = form_for @user, html: { class: 'form-horizontal' } do |f|
        = render 'shared/errors', obj: @user
        %header
          %h1 Your Account
        %fieldset
          .form-group
            = f.label :email, "Email Address", class: "control-label col-sm-3"
            .col-sm-4
              = f.email_field :email, class: "form-control"
          .form-group
            = f.label :password, class: "control-label col-sm-3"
            .col-sm-4
              = f.password_field :password, class: 'form-control'
          .form-group
            = f.label :full_name, "Full Name", class: "control-label col-sm-3"
            .col-sm-4
              = f.text_field :full_name, class: "form-control"
        %fieldset.actions.form-group
          .col-sm-8.col-lg-offset-3
            = f.submit "Update", class: 'btn btn-primary'
            = link_to "Cancel", account_path

app/views/users/new.html.haml
%script(src="https://js.stripe.com/v3/")
= javascript_include_tag "stripe-payment"

%section.register.container
  .row
    .col-sm-10.col-sm-offset-1
      = form_for @user, html: { class: "", id: "payment-form" } do |f|
        %header
          %h1 Register
        %fieldset
          .form-group
            = f.label :email, "Email Address"
            .row
              .col-sm-4
                = f.email_field :email
          .form-group
            = f.label :password, "Password"
            .row
              .col-sm-4
                = f.password_field :password
          .form-group
            = f.label :full_name, "Full Name"
            .row
              .col-sm-4
                = f.text_field :full_name
          = hidden_field_tag :invitation_token, @invitation_token
        %fieldset
          .form-group
            .row
              .col-sm-8
                %strong.row Credit Card Information
                #card-element
        %fieldset
          .from-group
            #card-errors
            %br

        %fieldset.form-group.action
          %input(type="submit" value="Sign Up" class="btn btn-primary")
        %hr
        = link_to "Go to Login", login_path, style: "color: blue"

:javascript
  window.stripe_key = "#{ENV['STRIPE_PUBLISHABLE_KEY']}"

app/views/users/plan_and_billing.html.haml
%section.billing.container
  .row
    .col-sm-10.col-sm-offset-1
      .plan_and_payments
        %section.plan
          %header
            %h1 Billing
          - if @customer.any_subscriptions?
            %table.table
              %thead
                %tr
                  %th
                  %th Next Billing Date
                  %th Price
              %tbody
                %tr
                  %td= @customer.plan_name
                  %td= @customer.next_payment_date
                  %td= @customer.plan_cost
          = button_to "Cancel Service", nil, name: "cancel", class: "btn btn-default"

          %section.payment_history
            %header
              %h3 Payment History
            %table.table
              %thead
                %tr
                  %th Date
                  %th Service Duration
                  %th Total
              %tbody
                - @invoices.each do |invoice|
                  %tr
                    %td= invoice.date
                    %td= invoice.service_duration
                    %td= invoice.total

app/views/users/show.html.haml
%section.user.container
  .row
    .col-sm-10.col-sm-offset-1
      %article
        %header
          %img(src="http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(@user.email.downcase)}?s=40")
          %h2 #{@user.full_name}'s video collections (#{@user.queue_items.count})
          = link_to "Follow", relationships_path(leader_id: @user.id), method: :post, class: "btn btn-default" if current_user.can_follow?(@user)
        %table.table
          %thead
            %tr
              %th(width="30%") Video Title
              %th(width="15%") Genre
          %tbody
            - @user.queue_items.each do |queue|
              %tr
                %td
                  = link_to queue.video.title, queue.video
                %td
                  = link_to queue.category_name, queue.category

%section.user_reviews.container
  .row
    .col-sm-10.col-sm-offset-1
      %header
        %h3 #{@user.full_name}'s Reviews (#{@user.reviews.count})
      %ul
        - @user.reviews.each do |review|
          %article.review
            %li.row
              .col-sm-2
                %p
                  = link_to review.video.title, review.video
                %col Rating: #{review.rating} / 5
              .col-sm-8
                %p= review.content