config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  mount StripeEvent::Engine, at: '/stripe_events'

  root to: 'pages#front'

  get 'ui/:name', to: 'ui#index'

  namespace :admin do
    resources :videos, only: [:new, :create]
    resources :payments, only: [:index]
  end

  get "home", to: "videos#index"

  get "register", to: "users#new"
  get "register/:token", to: "users#new_with_invitation_token", as: "register_with_token"
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'forgot_password', to: 'forgot_passwords#new'
  resources :forgot_passwords, only: [:create]
  get 'forgot_password_confirmation', to: 'forgot_passwords#confirm'
  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: 'pages#expired_token'

  resources :users, only: [:create, :show, :update]
  get 'account', to: 'users#edit'
  get 'billing', to: 'users#plan_and_billing'
  post 'billing', to: 'users#plan_and_billing'

  resources :videos, only: [:index, :show] do
    collection do
      post :search, to: "videos#search"
      get :advanced_search, to: "videos#advanced_search"
    end

    resources :reviews, only: [:create]
  end

  resources :categories, only: [:index, :show]

  get 'my_queue', to: 'queue_items#index'
  resources :queue_items, only: [:create, :destroy]
  post 'update_queue', to: 'queue_items#update_queue'

  get 'people', to: 'relationships#index'
  resources :relationships, only: [:create, :destroy]

  resources :invitations, only: [:new, :create]
end

app/models/video.rb
class Video < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  index_name ["ecomrails", Rails.env].join("_")

  # default_scope { order('created_at DESC') }

  # has_many :videos
  # belongs_to :category
  has_many :video_categories
  has_many :categories, through: :video_categories

  has_many :reviews

  validates :title, presence: true, uniqueness: true
  validates :description, presence: true, uniqueness: true
  # validates :video_url, presence: true, uniqueness: true

  mount_uploader :large_cover, LargeCoverUploader
  mount_uploader :small_cover, SmallCoverUploader

  def self.search_by_title(term)
    return [] if term.blank?
    where("LOWER(title) LIKE ?", "%#{term.downcase}%").order("created_at DESC")
  end

  def rating
    reviews.average(:rating).round(1) if reviews.average(:rating)
  end

  # override what data will be send to elasticsearch for indexing
  def as_indexed_json(options={})
    as_json(
      methods: [:rating],
      only: [:title, :description],
      include: {
        reviews: { only: [:content] }
      }
    )
  end

  # search via elasticsearch
  def self.search(search_term, options={})
    query = {
      query: {
        bool: {
          must: {
            multi_match: {
              query: search_term,
              fields: ["title^100", "description^50"],
              operator: "and"
            }
          }
        }
      }
    }

    if search_term.present? && options[:reviews].present?
      query[:query][:bool][:must][:multi_match][:fields] << "reviews.content"
    end

    if options[:rating_from].present? || options[:rating_to].present?
      query[:query][:bool][:filter] = {
        range: {
          rating: {
            gte: (options[:rating_from] if options[:rating_from].present?),
            lte: (options[:rating_to] if options[:rating_to].present?)
          }
        }
      }
    end

    __elasticsearch__.search(query)
  end
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < AdminController
  def new
    @video = Video.new
  end

  def create
    @video = Video.new video_params
    if @video.save
      flash[:success] = "You created new video"
      redirect_to new_admin_video_path
    else
      flash[:danger] = "There are invalid inputs"
      render :new
    end
  end

  private

  def video_params
    params.require(:video).permit(
      :title,
      :description,
      :small_cover,
      :large_cover,
      :video_url,
      category_ids: []
    )
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show]
  before_action :require_user
  # before_action :require_creator, only: [:edit, :update]

  def index
    # @videos = Video.all
    @categories = Category.all
  end

  def show
    @reviews = @video.reviews
  end

  def search
    @videos = Video.search_by_title(params[:term])
  end

  def advanced_search
    @videos = []
    options = {
      reviews: params[:reviews],
      rating_from: params[:rating_from],
      rating_to: params[:rating_to]
    }

    if params[:query]
      @videos = Video.search(params[:query], options).records.to_a
    end
  end

  private

  def set_video
    @video = VideoDecorator.decorate(Video.find(params[:id]))
  end
end

app/views/videos/advanced_search.html.haml
%section.advanced_search.container
  = form_tag advanced_search_videos_path, class: "form-horizontal", method: :get do
    %header
      %h1 Advanced Search
    .form-group
      .col-sm-6
        = search_field_tag :query, params[:query], placeholder: "Search videos by title, description", class: "form-control"
    .form-group
      .col-sm-6
        .checkbox
          = label_tag :reviews do
            = check_box_tag :reviews, true, params[:reviews].present?
            Include Reviews
    .form-group
      .row.average_rating_label Average Rating
      = label_tag :rating_from, "From", class: "col-sm-1 control-label"
      .col-sm-2
        = select_tag :rating_from, options_for_select((10..50).map { |num| num / 10.0 }, params[:rating_from]), prompt: "-", class: 'form-control'
      = label_tag :rating_to, "To", class: "col-sm-1 control-label"
      .col-sm-2
        = select_tag :rating_to, options_for_select((10..50).map { |num| num / 10.0 }, params[:rating_to]), prompt: "-", class: 'form-control'
    .form-group
      .col-sm-6
        = button_tag(type: "submit", class: "btn btn-primary") do
          %span.glyphicon.glyphicon-search
          Search
  %hr
  - if params[:query].present?
    %h2.results_count Results: #{@videos.count} videos found
    - @videos.each do |video|
      %article.video.row
        .video_data
          %figure.col-sm-2
            %img(src="#{video.small_cover_url}" alt="video cover")
          .video_body.col-sm-10
            %header
              %h3
                Video
                %em.label.label-highlight= video.title
            %p.video_description= video.description
            %hr
            .details
              %span.average_rating Average rating: #{video.rating || "N/A"}
              %span.reviews_count #{video.reviews.count} reviews
            %footer.video_review= video.reviews.count > 0 ? video.reviews.first.content : "N/A"

app/views/videos/index.html.haml
- @categories.each do |category|
  %article.video_category
    %header
      %h3= link_to category.name, category_path(category)
    .videos.row
      - category.recent_videos.each do |video|
        .video.col-sm-2
          = link_to video_path(video) do
            %img(src="#{video.small_cover}")

app/views/videos/search.html.haml
%article.video_category
  .videos.row
    - @videos.each do |video|
      .video.col-sm-2
        = link_to video_path(video) do
          %img(src="#{video.small_cover}")

app/views/videos/show.html.haml
%article.video
  .container
    .row
      .video_large_cover.col-sm-7.col-sm-offset-1
        %img(src="#{@video.large_cover}")
      .video_info.col-sm-3
        %header
          %h3= @video.title
          %span Rating:
          = @video.rating
        %p= @video.description
        .actions
          %a.btn.btn-primary(href="#{@video.video_url}" target="_blank") Watch Now
          = link_to "+ My Queue", queue_items_path(video_id: @video.id), method: :post, class: "btn btn-default" unless current_user.queued_video?(@video)

%section.reviews.container
  .row
    .col-sm-10.col-sm-offset-1
      = form_for [@video, Review.new] do |f|
        %fieldset
          .form-group
            %label Rate this video
            = f.select :rating, options_for_video_reviews
          .form-group
            %label Write Review
            .row
              .col-sm-8
                = f.text_area :content, rows:6, class: "form-control"
        %fieldset.form-group.actions.clearfix
          %input(type="submit" value="Submit" class="btn")
          = link_to "Cancel", @video
      %header
        %h3 User Reviews (#{@reviews.count})
      %ul
        - @reviews.each do |review|
          %article.review
            %li.row
              .col-sm-2
                %span Rating: #{review.rating} / 5
                %p
                  by
                  = link_to review.user.full_name, review.user
              .col-sm-8
                %p= review.content