config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  mount StripeEvent::Engine, at: '/stripe_events'

  root to: 'pages#front'

  get 'ui/:name', to: 'ui#index'

  namespace :admin do
    resources :videos, only: [:new, :create]
    resources :payments, only: [:index]
  end

  get "home", to: "videos#index"

  get "register", to: "users#new"
  get "register/:token", to: "users#new_with_invitation_token", as: "register_with_token"
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'forgot_password', to: 'forgot_passwords#new'
  resources :forgot_passwords, only: [:create]
  get 'forgot_password_confirmation', to: 'forgot_passwords#confirm'
  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: 'pages#expired_token'

  resources :users, only: [:create, :show, :update]
  get 'account', to: 'users#edit'
  get 'billing', to: 'users#plan_and_billing'
  post 'billing', to: 'users#plan_and_billing'

  resources :videos, only: [:index, :show] do
    collection do
      post :search, to: "videos#search"
      get :advanced_search, to: "videos#advanced_search"
    end

    resources :reviews, only: [:create]
  end

  resources :categories, only: [:index, :show]

  get 'my_queue', to: 'queue_items#index'
  resources :queue_items, only: [:create, :destroy]
  post 'update_queue', to: 'queue_items#update_queue'

  get 'people', to: 'relationships#index'
  resources :relationships, only: [:create, :destroy]

  resources :invitations, only: [:new, :create]
end

app/views/shared/_errors.html.haml
- if obj.errors.full_messages.any?
  %div.alert.alert-danger
    - obj.errors.full_messages.each do |msg|
      %p= msg

app/views/shared/_header.html.haml
%section#top-header.row
  %h1.col-md-2
    = link_to "EcomRails", root_path
  - if current_user
    %ul.col-md-4.clearfix
      %li= link_to "Videos", videos_path
      %li= link_to "My Queue", my_queue_path
      %li= link_to "People", people_path
      %li= link_to "Advanced Search", advanced_search_videos_path
    = form_tag search_videos_path, class: "col-md-5 navbar-form" do
      .form-group
        %input.form-control(name="term" type="text" placeholder="Search for videos here")
      %button.btn.btn-default(type="submit") Search
    #user_links.pull-right
      %ul
        %li.dropdown.custom
          %a(href="#" id="dlabel" role="button" data-toggle="dropdown" class="dropdown-toggle" data-target="#")
            Welcome, #{current_user.full_name}
            %b.caret
          %ul.dropdown-menu.custom(role="menu" aria-labelledby="dlabel")
            %li
              = link_to "Invite a friend", new_invitation_path
              = link_to "Account", account_path
              = link_to "Plan and Billing", billing_path
              - if current_user.admin?
                = link_to "Add Video", new_admin_video_path
                = link_to "View Payments", admin_payments_path
              = link_to "Log out", logout_path

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  #flash-msg(class="alert alert-#{name}")
    %a.close(data-dismiss='alert') &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

:javascript
  var msg = document.getElementById('flash-msg');
  if (msg) {
    var self = msg;
    msg.onclick = () => self.remove()
  }